window.DASHBOARD_DATA = {
  title: "NozaBoard",
  lastUpdated: "2026-03-29 09:26",
  tools: [
    { name: "Slack", status: "active", icon: "💬", details: "送信・下書き・チャンネル検索・リアクション・ブックマーク追加対応。xoxpトークンで認証。" },
    { name: "Gmail", status: "active", icon: "📧", details: "MCP経由で操作。送信・下書き・検索・ラベル管理。workspace-mcp OAuth認証。" },
    { name: "Google Spreadsheet", status: "active", icon: "📊", details: "REST API直接呼び出し（MCP経由ではない）。読み書き両対応（2026-03-27にread/write化）。" },
    { name: "Google Drive", status: "active", icon: "📁", details: "フルアクセス（読取・作成・コピー・移動）。2026-03-19にreadonlyからフルに変更。" },
    { name: "Google Calendar", status: "active", icon: "📅", details: "workspace-mcp経由。予定の取得・登録。gcp-oauth.keys2.jsonで認証。" },
    { name: "Google Forms", status: "active", icon: "📋", details: "Forms API + Apps Script API。テンプレコピー→リネーム→Apps Script自動生成→Webアプリデプロイ→回答スプシ作成。OAuth 8スコープ。" },
    { name: "Zoom", status: "active", icon: "🎥", details: "Server-to-Server OAuth。会議作成→Googleカレンダー転記→クリップボードコピー。" },
    { name: "Box", status: "active", icon: "📦", details: "OAuth API + Box Drive（ローカルファイルシステム同期）。出力先: 野沢用/claude/output/" },
    { name: "OpenAI API", status: "active", icon: "🧠", details: "GPT-4o（テキスト分析）、GPT-4o-mini（Camp Dashboard Slack解析）、gpt-image-1（画像生成）。環境変数OPENAI_API_KEYで認証。" },
    { name: "DeepL API", status: "active", icon: "🌐", details: "Free プラン（月50万文字まで無料）。環境変数DEEPL_API_KEYで認証。" },
    { name: "GitHub Actions", status: "active", icon: "⚙️", details: "claude-topリポジトリで稼働。daily-mail-reportワークフロー（毎朝8:00 JST）。Secrets設定済み。" },
    { name: "Firebase", status: "active", icon: "🔥", details: "3プロジェクト稼働中: dik-lounge（DIK Lounge）、aritomo-memo（メモアプリ）、camp-dashborad（Camp Dashboard）。Realtime DB + Email/Password Auth。" },
    { name: "Cloudflare Workers", status: "active", icon: "☁️", details: "Camp Dashboard用バックエンド。Slack Event→GPT-4o-mini解析→Firebase書き込み。Secrets 9個設定済み。" },
    { name: "Microsoft Graph", status: "pending", icon: "🏢", details: "Azure ADアプリ登録済み（Claude Code Automation）。Teams Forms APIは非対応のため手動運用。microsoft-token.jsonをBox/tokens/に保存。" },
    { name: "Notion", status: "pending", icon: "📝", details: "未連携。Internal Integration Tokenの発行が必要。" },
  ],
  tasks: [
    { id: 0, title: "事前mtg資料作成", status: "completed", notes: "/事前mtg作成 スキル化済み", details: "企業名と日付を指定するだけで、テンプレートコピー→スプシからデータ転記→本社住所WebSearch→カレンダー算出→pptx生成まで一気通貫で実行。python-pptxベース。" },
    { id: 1, title: "復習リマインドメール", status: "pending", notes: "スキル未完成（TODO残り）", details: "toB管理表から復習flg>=1の案件をピックアップし、リマインドメールの下書きを作成する。メール文案テンプレート待ち。" },
    { id: 2, title: "報告資料自動生成", status: "completed", notes: "/report スキル化済み", details: "アンケートExcel→集計→テンプレPPTX転記を自動化。満足度・理解度・Excel使用時間・効果実感・感想スライド対応。チャートCOM更新、ピクセル幅ベース改行。ExcelCamp・D-Wind研修対応。report_helpers.py汎用モジュール化済み。" },
    { id: 3, title: "Zoom URL発行+Gカレ転記", status: "completed", notes: "/zoom スキル化済み", details: "Zoom会議作成→GoogleカレンダーにURL転記→クリップボードにコピー。zoom_cal.pyで一発実行。引数あり/なし両対応。" },
    { id: 4, title: "請求書作成→PDF→Box保存", status: "in-progress", notes: "単社モードOK、バッチ未実装", details: "金額スプシ・toB管理スプシ・見積書を照合し、Excelテンプレートに転記→PDF出力→Box保存。単社モードは動作確認済み。バッチモード（複数社一括）は未実装。" },
    { id: 5, title: "請求書送付メール下書き", status: "pending", notes: "#4の後工程", details: "請求書作成後にGmailで送付メールの下書きを自動作成する。#4のバッチモード完了後に着手予定。" },
    { id: 6, title: "教材作成+復習フォーム", status: "completed", notes: "/教材作成 スキル化済み", details: "テンプレ教材コピー→フォルダリネーム→復習ドリル★Summary更新→Google Formsテンプレコピー→Apps Script自動生成→回答スプシ作成→QR生成→ドリルにURL+QR埋め込み→Slackブックマーク追加。2Phase構成（Phase1:フォーム作成、Phase2:教材作成+QR埋め込み）。zipfile直接編集方式。" },
    { id: 7, title: "メールレポート→Slack投稿", status: "in-progress", notes: "v5稼働中、GPT-4oで精度改善中", details: "GitHub Actionsで毎朝8:00 JSTに実行。Gmail→スレッド分析→GPT-4oで要約・タスク抽出→Slackチャンネル投稿。v5でバグ修正・通知フィルタ強化・返信検出精度向上済み。" },
    { id: 8, title: "DIK Lounge", status: "completed", notes: "v0.8.2 公開済み", details: "リアルタイムチャット、スタンプ32種、2D空間(PC)、アバターストリップ(モバイル)、アバターカスタマイズ(色8色・帽子5種・顔6種)、背景テーマ5種(Space/Ocean/Forest/Sunset/Cafe)全員同期・装飾アニメーション付き、入退室通知、在室数表示、タブ通知。Firebase Realtime DB。GitHub Pages公開。" },
    { id: 9, title: "Camp Dashboard", status: "completed", notes: "全機能公開済み", details: "5タブ(概要/検討事項/タスク/タイムライン/記録)+記録サブタブ5種。Slack連携(スタンプ→GPT-4o-mini解析→自動登録)。Ctrl+Kクイック検索、Alt+数字タブ切替。ダーク/ライト切替。Cloudflare Workers+Firebase。リアルタイムプレゼンス。URL: camp-dashboard。" },
    { id: 10, title: "aritomo-memo", status: "completed", notes: "デプロイ済み", details: "3タブ(カレンダー/リスト/行きたいところ)+メモタブ。記念日ハードコード。スワイプ操作(完了/削除)。PCホバー操作。カレンダースワイプ月移動。NozaBoard風ダークUI+薄ピンクライト。Firebase Email/Password Auth。GitHub Pages公開。" },
    { id: 11, title: "自分専用CLIエディター開発", status: "pending", notes: "VS Code代替・理想の画面設計", details: "VS Codeの代替として自分の理想の画面設計でCLIエディターを開発。GitHub連携必須。良いものが作れたら2端末で使えるようにする（npm/GitHub Releases等で配布）。" },
  ],
  skills: [
    { name: "事前mtg作成", desc: "研修の事前ミーティングpptxを自動生成", invocable: true, details: "企業名と事前mtg日付を指定するだけで、テンプレートコピーからデータ転記まで一気通貫で実行。WebSearchで本社住所取得、build_cal.pyで報告会候補日算出も含む。" },
    { name: "zoom", desc: "Zoom URL発行→Googleカレンダー転記→クリップボード", invocable: true, details: "引数あり: トピック・開始時刻・時間を指定。引数なし: 対話形式で入力。Zoom API（S2S OAuth）→ Google Calendar API → クリップボード。" },
    { name: "invoice", desc: "請求書作成→PDF→Box保存", invocable: true, details: "金額スプシ・toB管理スプシ・見積書を照合。Excelテンプレートに転記→COM経由でPDF出力→Box保存。単社/バッチ両モード対応予定。" },
    { name: "report", desc: "研修報告資料を自動生成", invocable: true, details: "アンケートExcel→集計(report_aggregate.py)→テンプレPPTX転記(report_fill.py)。ExcelCamp・D-Wind研修対応。チャートCOM更新、ピクセル幅ベース改行(正答率100%)。report_helpers.py汎用モジュール。" },
    { name: "教材作成", desc: "教材コピー+復習フォーム+QR埋め込み一気通貫", invocable: true, details: "Phase1: make_forms.py(Formsテンプレコピー→Apps Script→回答スプシ→QR)。Phase2: make_materials.py(テンプレ教材コピー→★Summary更新→QR+URL埋め込み)。zipfile直接編集方式。ExcelCampのみ対応。" },
    { name: "復習リマインド", desc: "復習リマインドメール下書き作成", invocable: true, details: "toB管理表から復習flg>=1の案件をピックアップ。メール文案テンプレートに基づいてGmail下書きを作成。（開発中）" },
    { name: "selfupdate", desc: "メモリ・スキル・引き継ぎを一括確認&更新", invocable: true, details: "セッション開始時は引き継ぎ確認+自動実行、終了時はhandoff.json・メモリ・スキル・STRUCTURE.mdを一括更新。PC自動判定(pc-identity.json)。" },
    { name: "skillupdate", desc: "セッション中の知見をスキル・メモリに反映", invocable: true, details: "セッション中の技術的知見・改善をスキルSKILL.md・メモリに反映し、両PC同期用のhandoff引き継ぎも生成する。" },
    { name: "box", desc: "Box操作（検索・閲覧・DL・フォルダ操作）", invocable: false, details: "Box API + Box Drive（ローカル同期）。ファイル検索・閲覧・ダウンロード・フォルダ作成・移動。Box Driveパスで直接ファイルアクセス可能。" },
    { name: "gmail", desc: "Gmail操作（検索・閲覧・送信・下書き）", invocable: false, details: "MCP経由でGmail API操作。野沢の文体ルール（90通分析ベース）に従ったメール下書き生成。返信時のスレッド維持設定も自動。" },
    { name: "slack", desc: "Slack操作（メッセージ送信・チャンネル検索）", invocable: false, details: "メッセージ送信・下書き作成・チャンネル検索・ブックマーク追加。野沢の文体ルール（30件分析ベース）準拠。50音番号マッピングでチャンネル検索。" },
    { name: "spreadsheet", desc: "Google Spreadsheet操作（読取・書込・検索）", invocable: false, details: "REST API直接呼び出し（MCP経由ではない）。読み書き両対応。トークン自動リフレッシュ。toB管理スプシ・金額スプシ等。" },
    { name: "schedule", desc: "日程調整（空き時間確認・候補日抽出）", invocable: false, details: "Googleカレンダーから空き時間を確認し、候補日を抽出する。" },
    { name: "image-gen", desc: "OpenAI APIによる画像生成", invocable: false, details: "gpt-image-1モデルで画像生成。1024x1024〜1536x1024対応。出力先: Box野沢用/claude/output/。1枚$0.04〜0.10。" },
    { name: "deepl", desc: "DeepL APIによる高品質翻訳", invocable: false, details: "Free プラン（月50万文字無料）。日英・英日など多言語対応。教材の多言語化に使用。" },
    { name: "pptx作成", desc: "PowerPointスライド自動生成", invocable: false, details: "python-pptxベース。Meiryo UIフォント（East Asian対応）。ノイズ除去ガイドライン準拠。チャートCOM更新対応。" },
    { name: "4月Camp募集", desc: "外部委託インストラクター募集自動化", invocable: false, details: "toB管理スプシ+インターンシフトスプシ分析→超絶/とても分類→Slack下書き一括作成。毎年3月中旬〜下旬に実行。" },
  ],
  workflows: [
    { name: "daily-mail-report", desc: "毎朝メール要約レポートをSlackに自動投稿", detail: "毎日 08:00 JST / Python 3.12 / GPT-4o", status: "running", details: "Gmail API→スレッド全文取得→通知フィルタ→返信状況分析→GPT-4oで要約・タスク抽出→Slackチャンネル(00_野沢ﾒｰﾙ_ﾀｽｸ整理)投稿。Secrets: GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET, GMAIL_REFRESH_TOKEN, OPENAI_API_KEY, SLACK_TOKEN, SLACK_CHANNEL_ID" },
  ],
};
